In [59]:
import numpy as np
import pandas as pd 

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [60]:
# defining dtypes upon reading in data to keep FIPS as 5 digit code
dtypes_dict = {
 'FIPS': 'object',
 'State': 'object',
 'County': 'object',
 'Deaths': 'float64',
 'Years of Potential Life Lost Rate': 'float64',
 '% Fair or Poor Health': 'float64',
 'Average Number of Physically Unhealthy Days': 'float64',
 'Average Number of Mentally Unhealthy Days': 'float64',
 '% Low birthweight': 'float64',
 '% Smokers': 'float64',
 '% Adults with Obesity': 'float64',
 'Food Environment Index': 'float64',
 '% Physically Inactive': 'float64',
 '% With Access to Exercise Opportunities': 'float64',
 '% Excessive Drinking': 'float64',
 '# Alcohol-Impaired Driving Deaths': 'float64',
 '# Driving Deaths': 'float64',
 '% Driving Deaths with Alcohol Involvement': 'float64',
 '# Chlamydia Cases': 'float64',
 'Chlamydia Rate': 'float64',
 'Teen Birth Rate': 'float64',
 '# Uninsured': 'float64',
 '% Uninsured': 'float64',
 '# Primary Care Physicians': 'float64',
 'Primary Care Physicians Rate': 'float64',
 'Primary Care Physicians Ratio': 'object',
 '# Dentists': 'float64',
 'Dentist Rate': 'float64',
 'Dentist Ratio': 'object',
 '# Mental Health Providers': 'float64',
 'Mental Health Provider Rate': 'float64',
 'Mental Health Provider Ratio': 'object',
 'Preventable Hospitalization Rate': 'float64',
 '% With Annual Mammogram': 'float64',
 '% Vaccinated': 'float64',
 '# Completed High School': 'int64',
 'Population': 'int64',
 '% Completed High School': 'float64',
 '# Some College': 'int64',
 'Population.1': 'int64',
 '% Some College': 'float64',
 '# Unemployed': 'float64',
 'Labor Force': 'float64',
 '% Unemployed': 'float64',
 '% Children in Poverty': 'float64',
 'Income Ratio': 'float64',
 '# Children in Single-Parent Households': 'float64',
 '# Children in Households': 'float64',
 '% Children in Single-Parent Households': 'float64',
 '# Associations': 'int64',
 'Social Association Rate': 'float64',
 'Annual Average Violent Crimes': 'float64',
 'Violent Crime Rate': 'float64',
 '# Injury Deaths': 'float64',
 'Injury Death Rate': 'float64',
 'Average Daily PM2.5': 'float64',
 '% Severe Housing Problems': 'float64',
 'Severe Housing Cost Burden': 'float64',
 'Overcrowding': 'float64',
 'Inadequate Facilities': 'float64',
 '% Drive Alone to Work': 'float64',
 '# Workers who Drive Alone': 'int64',
 '% Long Commute - Drives Alone': 'float64',
 'Water_Violation': 'int64'}

In [61]:
police = pd.read_csv('../data/police_scorecard_clean.csv', dtype={'location_name': object, 
                                                                  'state': object,
                                                                  'calc_overall_score': np.int64, 
                                                                  'FIPS': object})
mei = pd.read_csv('../data/mei_clean.csv')
ch_rankings = pd.read_csv('../data/chr_clean.csv', dtype=dtypes_dict)

In [62]:
ch_rankings.head()

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low birthweight,% Smokers,% Adults with Obesity,Food Environment Index,% Physically Inactive,% With Access to Exercise Opportunities,% Excessive Drinking,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,# Chlamydia Cases,Chlamydia Rate,Teen Birth Rate,# Uninsured,% Uninsured,# Primary Care Physicians,Primary Care Physicians Rate,Primary Care Physicians Ratio,# Dentists,Dentist Rate,Dentist Ratio,# Mental Health Providers,Mental Health Provider Rate,Mental Health Provider Ratio,Preventable Hospitalization Rate,% With Annual Mammogram,% Vaccinated,# Completed High School,Population,% Completed High School,# Some College,Population.1,% Some College,# Unemployed,Labor Force,% Unemployed,% Children in Poverty,Income Ratio,# Children in Single-Parent Households,# Children in Households,% Children in Single-Parent Households,# Associations,Social Association Rate,Annual Average Violent Crimes,Violent Crime Rate,# Injury Deaths,Injury Death Rate,Average Daily PM2.5,% Severe Housing Problems,Severe Housing Cost Burden,Overcrowding,Inadequate Facilities,% Drive Alone to Work,# Workers who Drive Alone,% Long Commute - Drives Alone,Water_Violation
0,01001,Alabama,Autauga,787.0,7830.053484,19.839179,4.501499,4.850214,9.201774,19.810766,33.0,6.7,30.6,69.130124,14.473886,19.0,57.0,33.333333,280.0,504.5,23.764041,4693.0,10.047314,26.0,46.76175,2139:1,19.0,34.00813,2940:1,16.0,28.63842,3492:1,6650.0,39.0,42.0,33076,37367,88.516606,8689,14362,60.499930,714.0,26172.0,2.728106,15.9,5.090408,3267.0,13205.0,24.740629,68,12.229996,148.5,272.282220,190.0,68.410043,10.4,13.630967,12.032598,1.116124,1.543576,85.788512,24635,38.3,0
1,01003,Alabama,Baldwin,3147.0,7680.477270,16.460675,3.647978,4.768294,8.292009,18.513318,30.0,7.8,24.7,73.713549,18.736958,53.0,179.0,29.608939,632.0,297.2,26.006904,22660.0,13.168983,153.0,70.17640,1425:1,110.0,49.27565,2029:1,220.0,98.55130,1015:1,3471.0,43.0,46.0,137219,151112,90.806157,33404,49776,67.108647,2653.0,97328.0,2.725834,13.5,4.385135,10321.0,46133.0,22.372271,229,10.503527,408.0,203.660396,777.0,72.878641,7.2,12.996651,11.987507,1.017929,0.334931,83.760106,93141,40.4,0
2,01005,Alabama,Barbour,515.0,11476.629416,29.841500,5.569267,5.590494,11.355311,25.530768,41.2,5.5,28.0,53.166770,12.466974,13.0,33.0,39.393939,191.0,755.8,37.114262,2310.0,13.504034,8.0,32.15305,3110:1,9.0,36.45791,2743:1,3.0,12.15264,8229:1,5314.0,44.0,39.0,13152,17964,73.213093,2379,6680,35.613772,324.0,8537.0,3.795244,41.0,5.981993,2707.0,5307.0,51.008103,19,7.636349,105.5,414.277861,98.0,76.988947,9.4,13.710555,12.594260,1.958651,0.652884,82.116389,8231,30.9,0
3,01007,Alabama,Bibb,476.0,12172.562382,23.853284,4.894377,5.271114,10.220994,23.084813,37.4,7.6,33.4,16.251364,15.420603,8.0,27.0,29.629630,139.0,613.2,37.786446,1764.0,10.599051,12.0,53.57143,1867:1,5.0,22.32741,4479:1,6.0,26.79289,3732:1,6690.0,33.0,40.0,12782,16168,79.057397,2483,6186,40.139024,266.0,8685.0,3.062752,25.9,5.002608,1404.0,4586.0,30.614915,19,8.482143,19.5,89.349126,119.0,105.601306,10.0,9.255242,8.263736,0.563991,0.563991,87.057671,8167,52.0,0
4,01009,Alabama,Blount,1100.0,11096.050649,21.985610,4.986622,5.357809,7.430541,22.954959,33.0,7.9,33.3,15.634486,15.833284,15.0,82.0,18.292683,176.0,303.4,31.239778,6642.0,14.115997,12.0,20.74689,4820:1,11.0,19.02258,5257:1,10.0,17.29326,5783:1,4440.0,37.0,40.0,32028,39791,80.490563,7862,14102,55.750957,676.0,25331.0,2.668667,21.0,4.427838,3003.0,13372.0,22.457374,45,7.780083,279.0,482.690611,311.0,107.591609,10.6,10.125665,7.468859,1.812470,1.159981,87.519594,21690,57.9,0

In [63]:
police.head()

  location_name state  calc_overall_score   FIPS
0      new york    NY                  32  36061
1   los angeles    CA                  33  06037
2       chicago    IL                  24  17031
3       houston    TX                  48  48201
4       phoenix    AZ                  39  04013

In [64]:
police.dtypes

location_name         object
state                 object
calc_overall_score     int64
FIPS                  object
dtype: object

In [65]:
police['location_name'].nunique()

10368

In [66]:
mei.head()

  state        city  standard_score  flex_score  total_mei
0    AL      auburn              21           2         23
1    AL  birmingham              94           8        100
2    AL    florence               0           0          0
3    AL      hoover              12           0         12
4    AL  huntsville              20           0         20

In [67]:
mei.shape

(506, 5)

In [68]:
mei.dtypes

state             object
city              object
standard_score     int64
flex_score         int64
total_mei          int64
dtype: object

In [69]:
ch_rankings.head()

,FIPS,State,County,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low birthweight,% Smokers,% Adults with Obesity,Food Environment Index,% Physically Inactive,% With Access to Exercise Opportunities,% Excessive Drinking,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,# Chlamydia Cases,Chlamydia Rate,Teen Birth Rate,# Uninsured,% Uninsured,# Primary Care Physicians,Primary Care Physicians Rate,Primary Care Physicians Ratio,# Dentists,Dentist Rate,Dentist Ratio,# Mental Health Providers,Mental Health Provider Rate,Mental Health Provider Ratio,Preventable Hospitalization Rate,% With Annual Mammogram,% Vaccinated,# Completed High School,Population,% Completed High School,# Some College,Population.1,% Some College,# Unemployed,Labor Force,% Unemployed,% Children in Poverty,Income Ratio,# Children in Single-Parent Households,# Children in Households,% Children in Single-Parent Households,# Associations,Social Association Rate,Annual Average Violent Crimes,Violent Crime Rate,# Injury Deaths,Injury Death Rate,Average Daily PM2.5,% Severe Housing Problems,Severe Housing Cost Burden,Overcrowding,Inadequate Facilities,% Drive Alone to Work,# Workers who Drive Alone,% Long Commute - Drives Alone,Water_Violation
0,01001,Alabama,Autauga,787.0,7830.053484,19.839179,4.501499,4.850214,9.201774,19.810766,33.0,6.7,30.6,69.130124,14.473886,19.0,57.0,33.333333,280.0,504.5,23.764041,4693.0,10.047314,26.0,46.76175,2139:1,19.0,34.00813,2940:1,16.0,28.63842,3492:1,6650.0,39.0,42.0,33076,37367,88.516606,8689,14362,60.499930,714.0,26172.0,2.728106,15.9,5.090408,3267.0,13205.0,24.740629,68,12.229996,148.5,272.282220,190.0,68.410043,10.4,13.630967,12.032598,1.116124,1.543576,85.788512,24635,38.3,0
1,01003,Alabama,Baldwin,3147.0,7680.477270,16.460675,3.647978,4.768294,8.292009,18.513318,30.0,7.8,24.7,73.713549,18.736958,53.0,179.0,29.608939,632.0,297.2,26.006904,22660.0,13.168983,153.0,70.17640,1425:1,110.0,49.27565,2029:1,220.0,98.55130,1015:1,3471.0,43.0,46.0,137219,151112,90.806157,33404,49776,67.108647,2653.0,97328.0,2.725834,13.5,4.385135,10321.0,46133.0,22.372271,229,10.503527,408.0,203.660396,777.0,72.878641,7.2,12.996651,11.987507,1.017929,0.334931,83.760106,93141,40.4,0
2,01005,Alabama,Barbour,515.0,11476.629416,29.841500,5.569267,5.590494,11.355311,25.530768,41.2,5.5,28.0,53.166770,12.466974,13.0,33.0,39.393939,191.0,755.8,37.114262,2310.0,13.504034,8.0,32.15305,3110:1,9.0,36.45791,2743:1,3.0,12.15264,8229:1,5314.0,44.0,39.0,13152,17964,73.213093,2379,6680,35.613772,324.0,8537.0,3.795244,41.0,5.981993,2707.0,5307.0,51.008103,19,7.636349,105.5,414.277861,98.0,76.988947,9.4,13.710555,12.594260,1.958651,0.652884,82.116389,8231,30.9,0
3,01007,Alabama,Bibb,476.0,12172.562382,23.853284,4.894377,5.271114,10.220994,23.084813,37.4,7.6,33.4,16.251364,15.420603,8.0,27.0,29.629630,139.0,613.2,37.786446,1764.0,10.599051,12.0,53.57143,1867:1,5.0,22.32741,4479:1,6.0,26.79289,3732:1,6690.0,33.0,40.0,12782,16168,79.057397,2483,6186,40.139024,266.0,8685.0,3.062752,25.9,5.002608,1404.0,4586.0,30.614915,19,8.482143,19.5,89.349126,119.0,105.601306,10.0,9.255242,8.263736,0.563991,0.563991,87.057671,8167,52.0,0
4,01009,Alabama,Blount,1100.0,11096.050649,21.985610,4.986622,5.357809,7.430541,22.954959,33.0,7.9,33.3,15.634486,15.833284,15.0,82.0,18.292683,176.0,303.4,31.239778,6642.0,14.115997,12.0,20.74689,4820:1,11.0,19.02258,5257:1,10.0,17.29326,5783:1,4440.0,37.0,40.0,32028,39791,80.490563,7862,14102,55.750957,676.0,25331.0,2.668667,21.0,4.427838,3003.0,13372.0,22.457374,45,7.780083,279.0,482.690611,311.0,107.591609,10.6,10.125665,7.468859,1.812470,1.159981,87.519594,21690,57.9,0

In [70]:
ch_rankings.shape

(3141, 64)

In [71]:
df = pd.merge(police, mei, how='right', 
              left_on=['location_name', 'state'], right_on=['city', 'state'])

In [72]:
df.shape

(510, 8)

In [73]:
df.isnull().sum()

location_name         75
state                  0
calc_overall_score    75
FIPS                  75
city                   0
standard_score         0
flex_score             0
total_mei              0
dtype: int64

In [74]:
df.dropna(inplace=True)

In [75]:
df.head()

,location_name,state,calc_overall_score,FIPS,city,standard_score,flex_score,total_mei
0,auburn,AL,42.0,01081,auburn,21,2,23
1,birmingham,AL,43.0,01073,birmingham,94,8,100
2,florence,AL,40.0,01077,florence,0,0,0
3,hoover,AL,44.0,01073,hoover,12,0,12
4,huntsville,AL,46.0,01089,huntsville,20,0,20

In [76]:
# df['fips_county_code'] = df['fips_county_code'].astype(int)
df['calc_overall_score'] = df['calc_overall_score'].astype(int)

In [77]:
df = pd.merge(df, ch_rankings, how='left', 
         left_on='FIPS', right_on='FIPS')

In [78]:
df.shape

(435, 71)

In [79]:
df.columns[df.isna().any()].tolist()

['Food Environment Index',
 'Preventable Hospitalization Rate',
 '% With Annual Mammogram',
 '% Vaccinated',
 'Annual Average Violent Crimes',
 'Violent Crime Rate',
 'Average Daily PM2.5']

In [80]:
df.describe()

,calc_overall_score,standard_score,flex_score,total_mei,Deaths,Years of Potential Life Lost Rate,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Average Number of Mentally Unhealthy Days,% Low birthweight,% Smokers,% Adults with Obesity,Food Environment Index,% Physically Inactive,% With Access to Exercise Opportunities,% Excessive Drinking,# Alcohol-Impaired Driving Deaths,# Driving Deaths,% Driving Deaths with Alcohol Involvement,# Chlamydia Cases,Chlamydia Rate,Teen Birth Rate,# Uninsured,% Uninsured,# Primary Care Physicians,Primary Care Physicians Rate,# Dentists,Dentist Rate,# Mental Health Providers,Mental Health Provider Rate,Preventable Hospitalization Rate,% With Annual Mammogram,% Vaccinated,# Completed High School,Population,% Completed High School,# Some College,Population.1,% Some College,# Unemployed,Labor Force,% Unemployed,% Children in Poverty,Income Ratio,# Children in Single-Parent Households,# Children in Households,% Children in Single-Parent Households,# Associations,Social Association Rate,Annual Average Violent Crimes,Violent Crime Rate,# Injury Deaths,Injury Death Rate,Average Daily PM2.5,% Severe Housing Problems,Severe Housing Cost Burden,Overcrowding,Inadequate Facilities,% Drive Alone to Work,# Workers who Drive Alone,% Long Commute - Drives Alone,Water_Violation
count,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,434.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,435.000000,434.000000,434.000000,434.000000,4.350000e+02,4.350000e+02,435.000000,4.350000e+02,4.350000e+02,435.000000,435.000000,4.350000e+02,435.000000,435.000000,435.000000,435.000000,4.350000e+02,435.000000,435.000000,435.000000,431.000000,431.000000,435.000000,435.000000,433.000000,435.000000,435.000000,435.000000,435.000000,435.000000,4.350000e+02,435.000000,435.000000
mean,44.786207,60.650575,4.422989,63.829885,9115.855172,6861.056238,17.621227,4.001297,4.361272,8.082824,17.141800,29.284138,7.935023,21.281839,87.904528,19.414151,105.218391,396.710345,28.569387,5695.154023,584.038391,19.735131,87112.406897,10.006514,770.940230,87.700819,784.404598,78.368561,2868.760920,320.656537,3997.986175,42.771889,49.451613,5.381934e+05,6.266923e+05,89.365700,1.781894e+05,2.645957e+05,68.713584,17467.558621,4.787429e+05,3.523391,15.931494,4.748562,54142.094253,2.109606e+05,25.773798,662.535632,9.765989,4150.726218,403.376498,2818.243678,72.612729,8.218245,17.806902,14.741836,3.216277,1.051555,77.450207,4.477422e+05,30.585287,0.004598
std,6.889034,28.470086,4.521370,29.908671,13906.428754,1924.977647,3.975897,0.556506,0.526717,1.480801,3.502330,5.239754,0.788819,4.489210,10.339473,3.025919,160.756408,634.468978,8.087510,10386.729614,221.952119,9.448062,163748.984509,4.406453,1203.133199,31.708065,1403.524929,25.751695,5343.051066,168.922715,1096.811836,6.493631,6.764171,8.742791e+05,1.075828e+06,4.776734,3.032125e+05,4.671734e+05,8.154469,33949.400428,8.091553e+05,0.981177,6.169047,0.725179,90976.244167,3.571721e+05,7.272161,916.143752,3.698258,7822.522791,235.069489,3958.648914,21.800056,1.997954,4.799517,3.666992,2.479282,0.741545,7.966473,7.564714e+05,12.154005,0.067728
min,24.000000,0.000000,0.000000,0.000000,98.000000,2872.671890,9.847407,2.667134,2.974246,4.929721,7.075650,14.300000,2.800000,8.900000,43.281766,6.453001,1.000000,3.000000,8.024691,46.000000,130.400000,2.098695,1019.000000,2.764273,7.000000,31.169580,8.000000,24.335570,7.000000,25.506950,455.000000,27.000000,26.000000,6.603000e+03,6.953000e+03,65.721320,2.241000e+03,2.878000e+03,43.647279,235.000000,6.884000e+03,1.791881,3.600000,3.523520,562.000000,2.352000e+03,9.157569,16.000000,1.816098,11.000000,42.286840,29.000000,30.834150,3.900000,8.424818,6.047820,0.358491,0.000000,5.990142,7.104000e+03,5.100000,0.000000
25%,40.000000,41.500000,0.000000,44.000000,1704.500000,5479.707892,14.482033,3.560381,4.026301,6.976638,14.874051,25.350000,7.500000,17.800000,83.023146,17.631394,20.000000,70.000000,24.095715,727.000000,437.900000,12.416092,10050.000000,6.919239,122.000000,67.813700,98.000000,63.067630,382.000000,195.408275,3162.250000,39.000000,45.250000,8.681700e+04,9.751700e+04,87.446157,2.501800e+04,3.635400e+04,63.613493,2383.500000,7.591950e+04,2.833060,11.400000,4.276928,7268.500000,2.942100e+04,20.567968,149.000000,7.005754,397.500000,236.501945,550.500000,56.584489,7.000000,14.508992,12.131729,1.604802,0.729415,75.374711,7.052350e+04,20.900000,0.000000
50%,45.000000,61.000000,4.000000,64.000000,4377.000000,6681.863975,17.304336,4.034772,4.352698,7.970693,17.182413,29.800000,8.000000,21.800000,90.343894,19.046271,50.000000,173.000000,28.286853,2421.000000,563.600000,18.507527,29160.000000,9.254661,352.000000,84.660010,309.000000,75.324910,1179.000000,298.803750,4008.000000,43.000000,50.000000,2.271980e+05,2.582580e+05,90.064548,7.162700e+04,1.038040e+05,68.963853,6369.000000,1.969910e+05,3.343981,15.000000,4.655328,22719.000000,8.680700e+04,24.973469,368.000000,9.527044,1456.000000,361.235828,1352.000000,70.807222,8.200000,16.762452,14.078525,2.286609,0.931382,78.993448,1.792250e+05,30.300000,0.000000
75%,49.000000,87.500000,6.500000,93.500000,10226.000000,7954.911928,20.248989,4.380608,4.756732,8.789596,19.493794,33.000000,8.400000,24.100000,96.311757,21.262426,108.000000,372.000000,32.547397,5820.000000,689.050000,25.205033,71739.500000,12.432301,884.500000,103.032610,797.500000,90.183510,3371.000000,389.999815,4695.750000,47.000000,54.000000,5.790900e+05,6.383280e+05,92.730411,1.775660e+05,2.552215e+05,73.819614,18224.000000,4.838425e+05,4.018283,19.600000,5.064777,56476.500000,2.142100e+05,30.494012,822.000000,11.778234,4522.250000,489.965382,3380.000000,85.225997,9.400000,19.964195,17.075198,4.116118,1.161805,82.096025,4.632350e+05,39.750000,0.000000
max,65.000000,100.000000,19.000000,100.000000,84748.000000,16913.389014,34.857096,6.469784,6.178428,14.531523,27.555392,42.600000,9.600000,33.700000,100.000000,31.013699,866.000000,3594.000000,75.000000,67878.000000,1421.800000,57.262283,935213.000000,32.072500,7412.000000,290.957460,8999.000000,230.250100,36404.000000,991.907840,8826.000000,64.000000,67.000000,5.449836e+06,6.886895e+06,97.156184,1.919317e+06,3.003060e+06,87.569544,227288.000000,5.121584e+06,9.622022,39.000000,9.146811,556280.000000,2.208226e+06,52.713630,5843.000000,28.328612,49548.500000,1819.514406,20745.000000,196.634796,16.000000,32.922433,25.478690,14.043935,11.054895,88.392654,4.811408e+06,69.600000,1.000000

In [81]:
# Imputing Alexandria, VA Food Environment Index (from 2017) 8.7
# source: http://www.healthmattersalexandria.org/indicators/index/view?indicatorId=2362&localeId=2967

df.loc[416, 'Food Environment Index'] = 8.7

In [82]:
# When investigating other null values, Homer, AK was missing many values
# so I removed it instead of imputing multiple values for the same city
df.drop(index=10, inplace=True)

In [83]:
# imputing number of violent crimes per 
# source: https://www.neighborhoodscout.com/

df.loc[9, 'Annual Average Violent Crimes'] = 251
df.loc[12, 'Annual Average Violent Crimes'] = 48
df.loc[331, 'Annual Average Violent Crimes'] = 29

df.drop(columns='Violent Crime Rate', inplace=True)

In [84]:
df.loc[11, 'Average Daily PM2.5'] = 2.1

In [85]:
df.columns[df.isna().any()].tolist()

[]

### Ready to Look at Correlation/Models

In [ ]:
chr = pd.read_csv('../data/')